vimeo/VimeoUpload

VimeoUpload/Upload/Model/VideoSettings.swift

<b>Ticket</b>
https://vimean.atlassian.net/browse/VIM-3848
<b>Ticket Summary</b>
"Something strange occurred" alert when you upload video with just spaces in title
<b>Implementation Summary</b>
Trim whitespace from title before starting upload
How To Test
1. open the app 
2. upload your video 
3. tap on a video and set your title with only spaces 
4. tap [upload]
5. Title is now "Untitled"

Trims whitespace from title in VideoSettings

---

VimeoUpload/Descriptor System/DescriptorManager.swift
VimeoUpload/Upload/Descriptor System/New Upload (Private)/UploadDescriptor.swift

[VIM-3723](https://vimean.atlassian.net/browse/VIM-3723)
Initiating an upload or download from certain iOS8 devices (e.g. iOS 8.2) and immediately killing the app. Upon re-launching the app the download or upload would automatically restart instead of being flagged as a failure. 
Removed the check against `isNetworkCancellationError`. This seemed iffy for one, and it was included at the 11th hour before launch of Vimeo iOS v6.0. It also doesn't appear to be necessary. We should just let the error fall through and be captured by the normal error catch at the bottom of `taskDidComplete:`.
See ticket.

VIM-3723: Multitask cancellations are now always flagged as errors

---

VimeoUpload/Upload/Model/VideoSettings.swift

<b>Ticket</b>
https://vimean.atlassian.net/browse/VIM-3848
<b>Ticket Summary</b>
"Something strange occurred" alert when you upload video with just spaces in title
<b>Implementation Summary</b>
Trim whitespace from title before starting upload
How To Test
1. open the app 
2. upload your video 
3. tap on a video and set your title with only spaces 
4. tap [upload]
5. Title is now "Untitled"

VIM 3848: Removes some redundancy from VideoSettings

---

Examples/VimeoUpload-iOS/VimeoUpload-iOS.xcodeproj/project.pbxproj
Examples/VimeoUpload-iOS/VimeoUpload-iOS/Bridge.h
VimeoUpload.podspec
VimeoUpload/Descriptor System/ConnectivityManager.swift
VimeoUpload/Descriptor System/Descriptor.swift
VimeoUpload/Descriptor System/DescriptorManager.swift
VimeoUpload/Extensions/AFURLSessionManager+Extensions.swift
VimeoUpload/Networking/VimeoRequestSerializer.swift
VimeoUpload/Networking/VimeoResponseSerializer.swift
VimeoUpload/Networking/VimeoSessionManager.swift
VimeoUpload/UIKit/ALAssetHelper.swift
VimeoUpload/Upload/Descriptor System/Old Upload/OldUploadDescriptor.swift
VimeoUpload/Upload/Extensions/AFURLSessionManager+Upload.swift

[VIM-4015](https://vimean.atlassian.net/browse/VIM-4015)
Make this library consumable as a pod.
Total failure :imp:. The combination of iOS7 and Cocoapods and Objc and Swift creates a stew of frustration. This lays some groundwork for when we deprecate support for iOS7 in the Vimeo iOS app. But it does not make this library consumable as a pod. 
Confirm this library and its sample projects still build.

VIM-4015: Make VimeoUpload Consumable as a Cocoapod

---

VimeoUpload/VimeoUploader.swift

[CAM-287](https://vimean.atlassian.net/browse/CAM-287)
In order to track when an upload completes in Cameo we want the ability to set the ReachableDescriptorManager object's delegate in the VimeoUploader class.
The ReachableDescriptorManager class already allows it's delegate to be set in the initializer, I just added this parameter to the initializer for the VimeoUploader class so it can be passed in.
N/A

CAM-287: expose the ReachableDescriptorManager delegate

---

VimeoUpload/UIKit/Model/VIMALAsset.swift
VimeoUpload/Upload/Model/VideoSettings.swift

[CAM-208](https://vimean.atlassian.net/browse/CAM-208)
Add upload analytics to Cameo that mirror the ones implemented in Vimeo iOS.
In order to implement the same analytics in Cameo that Vimeo iOS has, I need to change the scope of certain properties and init functions so they can be accessed in Cameo.  This isn't an issue for Vimeo iOS because the upload library is not linked in as a module.
N/A

CAM-208: changing scope of some properties to public

---

VimeoUpload/Upload/Descriptor System/VideoDescriptorFailureTracker.swift

[CAM-279](https://vimean.atlassian.net/browse/CAM-279)
Ensure that videos can only be shared once they enter the .Available state. 
This ticket also included representing server-side upload state in UI. But this is premature. This needs to be thought through more thoroughly from product and design.
A variety of things: 
- Stripped CMProject status enum down into .Open and .Closed only. 
- Propagated this change throughout the codebase, fixed a few bugs that it triggered. 
- Changed name of `clipURL` to `videoLink`. 
- Using project identifier as the `descriptor.identifier` instead of the `videoURI`. 
- Setting `videoLink`, `videoURI`, and `videoResourceKey` on upload success only, instead of upfront.
- Changed how uploads are cancelled: centralized the logic, …

CAM-279: Upload Enhancements

---

Framework/VimeoUpload/VimeoUpload.xcodeproj/project.pbxproj
VimeoUpload/Upload/Descriptor System/Cameo/CAMUploadDescriptor.swift
VimeoUpload/Upload/Descriptor System/Cameo/CAMUploadReqest.swift
VimeoUpload/Upload/Descriptor System/Cameo/VimeoRequestSerializer+Thumbnail.swift
VimeoUpload/Upload/Descriptor System/Cameo/VimeoResponseSerializer+Thumbnail.swift
VimeoUpload/Upload/Descriptor System/Cameo/VimeoSessionManager+ThumbnailUpload.swift
VimeoUpload/Upload/Extensions/NSError+Upload.swift
VimeoUpload/Upload/Networking/Old Upload/VimeoSessionManager+OldUpload.swift

[CAM-308](https://vimean.atlassian.net/browse/CAM-308)
Create a new upload descriptor that encapsulates the create / upload / activate video steps and the create / upload / activate thumbnail steps.
I added a new CAMUploadDescriptor that is based on the OldUploadDescriptor class.  It performs the 4 step upload for video files and adds 3 additional steps for uploading a custom thumbnail.  New extensions for VimeoRequestSerializer, VimeoResponseSerializer, and VimeoSessionManager were added for thumbnail specific request / response handling.
N/A

CAM-308: Added a new upload descriptor for Cameo

---

VimeoUpload/Upload/Descriptor System/Cameo/CAMUploadDescriptor.swift
VimeoUpload/Upload/Descriptor System/Cameo/CAMUploadReqest.swift
VimeoUpload/Upload/Networking/New Upload (Private)/VimeoSessionManager+Upload.swift

N/A
Need to switch the CAMUploadDescriptor over to using the two step upload process so that we have a valid VIMVideo object in the VIMUploadTicket.
Added a new method to VimeoSessionManager+Upload so we can get a download task for the create video step.  Modified the CAMUploadDescriptor class to use the two step upload version for the create video step.  Removed the VideoSettings and ActivateVideo steps from the CAMUploadDescriptor.
N/A

CAM-XXX: Switch CAMUploadDescriptor to two step upload process

---

VimeoUpload/Upload/Operations/Async/ExportOperation.swift
VimeoUpload/Upload/Operations/Async/ExportQuotaOperation.swift
VimeoUpload/Upload/Operations/Private/ExportQuotaCreateOperation.swift
VimeoUpload/Upload/Operations/Private/RetryUploadOperation.swift

[VIM-4197](https://vimean.atlassian.net/browse/VIM-4197)
The asset for an iCloud video was not readily available for playback after being downloaded. We now pass the export session object into the `exportProgressBlock` so that a client can access the asset from an iCloud video for playback, via `exportSession.asset`.
- made `exportSession` property on `ExportOperation` accessible outside of class 
- new block type `ExportProgressBlock` includes an `exportSession` object as input parameter
- property `exportProgressBlock` on `ExportQuotaOperation` now has type `ExportProgressBlock` where we pass in the `exportSession`
See parent ticket.

VIM-4197: Resolve No Playback for iCloud Videos in Upload Preview

---

VimeoUpload/Upload/Descriptor System/Cameo/CAMUploadDescriptor.swift
VimeoUpload/Upload/Descriptor System/Cameo/VimeoSessionManager+ThumbnailUpload.swift
VimeoUpload/Upload/Descriptor System/New Upload (Private)/UploadDescriptor.swift
VimeoUpload/Upload/Descriptor System/Old Upload/OldUploadDescriptor.swift
VimeoUpload/Upload/Networking/Old Upload/VimeoSessionManager+OldUpload.swift

[VIM-4803](https://vimean.atlassian.net/browse/VIM-4803)
We were experiencing a memory / potentially zombie induced crash upon initiating one or more downloads. 
There were API changes in AFNetworking that made the progress object more accessible via a block. https://github.com/AFNetworking/AFNetworking/pull/3187
Our own API included a means to pass in an `AutoreleasingUnsafeMutablePointer<NSProgress?>` to keep track of this progress, if needed. 
Because we don't need to maintain a pointer to this progress object in our current implementation, and just discovered that doing so can introduce bugs, we removed this part of the API. 
See parent ticket.

VIM-4803: Download Crash

---

Dangerfile
circle.yml
fastlane/Fastfile

[CI-123](https://vimean.atlassian.net/browse/CI-123)
Report build results to PR comments. This feature was in already, but because there were two "builds" - iOS and iOS-Old, they were overwriting each other. This PR fixes that by separating the reports.
Updated Fastlane and Danger to generate and read separate build reports.
PR comment should include 2 separate reports.

CI-123 PR build reporting

---

VimeoUpload/UIKit/PHAssetHelper.swift

[AF-126](https://vimean.atlassian.net/browse/AF-126)
We used to store `PHImageManager.default()` in a property `imageManager`. The line that instantiate this property `imageManager` always gets called when we hit on the `Upload` button. In other words, every time we access to `PHAssetHelper`.
A crash would occur if there is a memory warning and the authorization to access to the library was turned off.
Note: In sync with the last comment on this post:
https://stackoverflow.com/questions/33266346/photos-framework-crash-this-application-is-not-allowed-to-access-photo-data
Completely removed the property and directly call `PHImageManager.default()` when needed.
- Run the main app on simulator
- Have the authorization to access to the Photo Library turned off. (go to settings, vimeo app, …

AF-126: Fix crash on PHImageManager.default()

---

Examples/VimeoUpload-iOS/VimeoUpload-iOS/ViewControllers/VideoSettingsViewController.swift
VimeoUpload/Upload/Model/VideoSettings.swift

[AF-105](https://vimean.atlassian.net/browse/AF-105)
This PR fixes the crashes occurring while attempting to upload a video via the sample app. Originally, the crash was reported for `VimeoUpload` target, which implements the two-step upload flow. Since two-step upload hasn't been available to the public yet, it was found that any current attempt to upload via this flow would not have the video object returned. That behavior caused the crash that multiple people have reported because the flow assumed the video object was always there. The change in the `VimeoUpload` target addresses this issue by safely unwrapping the video object &mdash; if it does not exist, then we show an alert to the user and not execute the remaining logic.
In addition, it was discovered that there was another bug …

AF-105: Fix Upload Example Crash

---

Examples/VimeoUpload-iOS/VimeoUpload-iOS/ViewControllers/VideoSettingsViewController.swift

N/A
This PR contains a new text for the alert appearing when the user attempts to upload a video via the two-step flow.
N/A
N/A
- Run the example with a third-party token and attempt to upload a video; make sure the new text is on the alert.

Change Alert Text of Two-Step Upload Flow

---

VimeoUpload/Descriptor System/ReachableDescriptorManager.swift

N/A
This PR assigns the shared container identifier to the upload background session's configuration. It is necessary to do so because Apple requires share extensions to have an upload background session to be associated with a shared container.
Added a shared container identifier argument to `ReachableDescriptorManager`'s constructor. In the constructor, we then set the identifier to the background configuration's `sharedContainerIdentifier` property.
N/A
N/A

Inject the shared container identifier string

---

Framework/VimeoUpload/VimeoUpload.xcodeproj/project.pbxproj
VimeoUpload/Upload/Networking/New Upload (Private)/VimeoRequestSerializer+Upload.swift
VimeoUpload/Upload/Networking/Shared/VimeoRequestSerializer+SharedUpload.swift

[VIM-6144](https://vimean.atlassian.net/browse/VIM-6144)
- To be compatible with API v3.4 and still have videos that are recognized as being in the uploading state (i.e. invisible to search results), we needed to explicitly say we are doing a pre upload by adding a parameter. (See ticket). 
- API issue linked for context https://github.vimeows.com/Vimeo-API/api/issues/2005
- Renamed file from old upload to shared upload given both new and old upload use API from this file
- Added parameters as per ticket specifications 
- Broke out literals into constants  
- N/A this can only be tested once other upload changes are in place. I verified that we are able to receive videos in the pre upload privacy state to test that this works with other changes. Will have other PR include that test.

 VIM-6144: Support pre upload for API v3.4

---

VimeoUpload/UIKit/Extensions/NSString+Conversions.swift

N/A
- Using `+` with string literals has poor type-checking performance, see [here](https://github.vimeows.com/MobileApps/Style-Guides/pull/34).
- Wherever we had `+` used with string literals, use string interpolation instead.
- Make sure interpolation replacements preserve semantics!

VIM-XXXX: Replace use of '+' with string interpolation

---

VimeoUpload/Descriptor System/DescriptorManager.swift
VimeoUpload/Descriptor System/DescriptorManagerArchiver.swift
VimeoUpload/Descriptor System/ReachableDescriptorManager.swift
VimeoUpload/Upload/Controllers/VideoDeletionManager.swift
VimeoUpload/Upload/Descriptor System/VideoDescriptorFailureTracker.swift

[VIM-6403](https://vimean.atlassian.net/browse/VIM-6403)
As the share extension's background session needs to be a singleton in order to work properly, there is no need for those `shouldLoadArchive` arguments anymore. We should remove them.
N/A
N/A
N/A

VIM-6403: Remove `shouldLoadArchive` Arguments

---

VimeoUpload/Descriptor System/DescriptorManager.swift

[VIM-6449](https://vimean.atlassian.net/browse/VIM-6449)
This PR introduces a generic invalidation error. We will send this error along with the invalidation notification instead of using the error object returned to us by `AFNetworking`.
If you look at the crash log from HockeyApp and the stack trace from the Xcode's Organizer window, you'll see that there was something wrong with `release` calls inside the Swift's standard library when we tried to cast `Error` to `NSError`, at line 201 of `DescriptorManager`. To understand why this casting occurred from the beginning, let's recall how background session's handoff process works.
When a long upload is performed from the share extension, and the …

VIM-6449: Add Generic Invalidation Error

---

VimeoUpload/Descriptor System/DescriptorManager.swift
VimeoUpload/Descriptor System/DescriptorManagerDelegate.swift
VimeoUpload/Upload/Descriptor System/DescriptorManagerTracker.swift

[VIM-6542](https://vimean.atlassian.net/browse/VIM-6542)
- Adds support for loss of connectivity during Fresnel tracking, which requires that the upload be cancelled and restarted when network connectivity comes back
- Adds delegate method for tracking resume after loss of connectivity 
- See client PR

VIM-6542: Handle connectivity loss

---

VimeoUpload/Upload/Extensions/AVAsset+Extensions.swift
VimeoUpload/Upload/Model/BlockTypes.swift

[VIM-6667](https://vimean.atlassian.net/browse/VIM-6667)
This PR converts the file's size's computation from `Float64` to `Double`.
N/A
N/A
N/A

VIM-6667: Correct Data Type of File's Size

---

VimeoUpload/Upload/Extensions/AVAsset+Extensions.swift
VimeoUpload/Upload/Model/BlockTypes.swift

N/A
This PR changes the asset's size calculation to `Double`-based.
N/A
N/A
N/A

VIM-XXXX: Share Extension Localytics

---

Framework/VimeoUpload/VimeoUpload.xcodeproj/project.pbxproj
VimeoUpload/Descriptor System/Descriptor.swift
VimeoUpload/Descriptor System/DescriptorManager.swift
VimeoUpload/Upload/Descriptor System/New Upload (Private)/UploadDescriptor.swift
VimeoUpload/Upload/Descriptor System/New Upload (Private)/UploadStrategy.swift
VimeoUpload/Upload/Extensions/Retriable.swift

[VIM-6707](https://vimean.atlassian.net/browse/VIM-6707)
This PR attempts to retry an GCS upload request whenever we encounter either a 404 or a 5xx status code.
See the client's PR for more detail.
- **`Retriable`**: Added the protocol to assist a descriptor in determining if it should retry.
- **`UploadDescriptor`**: Asked the upload strategy if it should retry.
- **`DescriptorManager`**: Retried a descriptor before checking for any error; also refactored the retry code into a separate function.
N/A
Run all unit tests. Check that they all pass.

VIM-6707: Handle GCS Response

---

VimeoUpload/Upload/Descriptor System/New Upload (Private)/UploadDescriptor.swift
VimeoUpload/Upload/Descriptor System/New Upload (Private)/UploadStrategy.swift
VimeoUpload/Upload/Networking/New Upload (Private)/VimeoSessionManager+Upload.swift
VimeoUpload/VimeoUploader.swift

[VIM-6601](https://vimean.atlassian.net/browse/VIM-6601)
Slight refactor of where upload parameters are set
- Makes upload strategy a stored property
- Moves upload parameters to be contained by the upload strategy 
- Make sure unit tests pass

VIM-6601: Slight refactor of where upload parameters are set

---

VimeoUpload/Descriptor System/Descriptor.swift
VimeoUpload/Descriptor System/DescriptorManager.swift
VimeoUpload/Upload/Descriptor System/New Upload (Private)/UploadDescriptor.swift
VimeoUpload/Upload/Extensions/Retriable.swift

[VIM-6785](https://vimean.atlassian.net/browse/VIM-6785)
- We want to limit the number of times that an upload will be retried to prevent an infinite loop where a corrupted/invalid request fails over and over.
**Retriable.swift**
- Add a new `attemptNumber` property that tracks how many times a `Retriable` object has been retried.
**Descriptor.swift**
- Add `attemptNumber` property required by `Retriable` protocol.
- Add new open `retry(sessionManager:)` method so that `Descriptor` can keep track of its own retries.
- When loading from a coder, just set `attemptNumber` to `0`, don't bother persisting to disk.
**DescriptorManager.swift**
- Use the new `retry(sessionManager:)` API in `Descriptor`
**UploadDescriptor.swift**
- Create new `Constants` struct and move coding keys into it.
- Add …

VIM-6785: Add max retries to GCS upload request

---

Examples/VimeoUpload-iOS/VimeoUpload-iOS.xcodeproj/project.pbxproj
Examples/VimeoUpload-iOS/VimeoUpload-iOSTests/URL+MIMETypeTests.swift
Framework/VimeoUpload/VimeoUpload.xcodeproj/project.pbxproj
VimeoUpload/Extensions/URL+MIMEType.swift
VimeoUpload/Upload/Networking/New Upload (Private)/VimeoRequestSerializer+Upload.swift
VimeoUpload/Upload/Networking/Shared/VimeoRequestSerializer+SharedUpload.swift

[VIM-6830](https://vimean.atlassian.net/browse/VIM-6830)
- Adds MIMEType information to create video request
- Adds extension on URL to provide MIMEType
- Parameter dictionary generated in new private method
- This dictionary is bundled with file size into new dictionary provided by `createFileParameters`
- This extension was adapted from  
- https://stackoverflow.com/questions/31243371/path-extension-and-mime-type-of-file-in-swift
- https://stackoverflow.com/questions/1363813/how-can-you-read-a-files-mime-type-in-objective-c
- Within the extension: We have ownership of the unmanaged object based on the Create Rule [described here](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-CJBEJBHHTh …

VIM-6830: Add MIMEtype to video creation

---

VimeoUpload/UIKit/PHAssetHelper.swift

[VIM-2226](https://vimean.atlassian.net/browse/VIM-2226)
- iOS 13 apparently returns a new error if the local asset is not available, which we were treating as a total failure. However, this error is returned even in the case where the asset is in iCloud, resulting in us reporting errors that don't indicate a total failure
- Changes for style guide.
- The only behavior change is in `func requestAsset(cell:cameraRollAsset:)`. Here, rather than treating an error as a failure, we quietly set the error on the asset for later use, and then assume that a `nil` asset means that it is available in iCloud. Thus, every cell for which the asset is not immediately available will have the "iCloud" label visible.
- Test as part of main app PR.

VIM-2226: Update handling of iCloud videos for iOS 13

---

Examples/VimeoUpload+Demos/ViewControllers/BaseCameraRollViewController.swift
Examples/VimeoUpload-iOS-OldUpload/VimeoUpload-iOS-OldUpload.xcodeproj/project.pbxproj
Examples/VimeoUpload-iOS-OldUpload/VimeoUpload-iOS-OldUpload/AppDelegate.swift
Examples/VimeoUpload-iOS-OldUpload/VimeoUpload-iOS-OldUpload/Bridge.h
Examples/VimeoUpload-iOS/VimeoUpload-iOS.xcodeproj/project.pbxproj
Examples/VimeoUpload-iOS/VimeoUpload-iOS/AppDelegate.swift
Examples/VimeoUpload-iOS/VimeoUpload-iOS/Bridge.h
Framework/VimeoUpload/VimeoUpload.xcodeproj/project.pbxproj
Podfile
Podfile.lock
VimeoUpload/Descriptor System/ConnectivityManager.swift
VimeoUpload/Descriptor System/Descriptor.swift
VimeoUpload/Descriptor System/DescriptorManager.swift
VimeoUpload/Extensions/AFURLSessionManager+Extensions.swift
VimeoUpload/Upload/Controllers/VideoDeletionManager.swift
VimeoUpload/Upload/Controllers/VideoRefreshManager.swift
VimeoUpload/Upload/Descriptor System/Cameo/CAMUploadDescriptor.swift
VimeoUpload/Upload/Descriptor System/New Upload (Private)/UploadDescriptor.swift
VimeoUpload/Upload/Descriptor System/Old Upload/OldUploadDescriptor.swift
VimeoUpload/Upload/Extensions/AFURLSessionManager+Upload.swift

N/A
We decided to fold all AFNetworking files into our own repo instead of managing them as an external dependency. This will allow us better control of file visibility and also what should/shouldn't be included.
The motivator for this change was an issue Magisto has started to encounter when consuming our library, where Apple is giving warnings for deprecated use of `UIWebView` which will soon end up in rejected submissions.
There is a PR on AFNetworking [here](https://github.com/AFNetworking/AFNetworking/issues/4428) that has been opened since late August and still waiting to be merged, which indicates the support for the library is slowing down substantially and we don't expect any major updates will be available that we may be able to take advantage of.
* Remove all AFNetworking …

Updates use of AFNetworking based on VimeoNetworking changes

---

Podfile
Podfile.lock
VimeoUpload/Upload/Descriptor System/Cameo/VimeoRequestSerializer+Thumbnail.swift
VimeoUpload/Upload/Networking/Shared/VimeoRequestSerializer+SharedUpload.swift

[VIM-XXXX](https://vimean.atlassian.net/browse/VIM-XXXX)
This is a simple refactor to accommodate changes on VimeoNetworking via [this PR](https://github.com/vimeo/VimeoNetworking/pull/368)
- Mostly replaces Stringy typed methods with the corresponding `enum` case.
- Build and run, ensure unit tests pass

VIM-XXXX: Refactors VimeoRequestSerializer API usage
